### ISSUE TITLE
Slim 3   Class 'Slim\View' and 'Slim\Middleware' not found

### ISSUE THREAD

**Issue by kriang69** [entomb/slim-json-api#34]
`Fatal error: Class 'Slim\View' not found in C:\xampp\htdocs\slim\test\vendor\entomb\slim-json-api\jsonAPI\JsonApiView.php on line 24`

`Fatal error: Class 'Slim\Middleware' not found in C:\xampp\htdocs\slim\test\vendor\entomb\slim-json-api\jsonAPI\JsonApiMiddleware.php on line 23`

**Comment by gricey432** [comment]
This is an issue because of the new way Slim 3.0 does middleware, see #27 for a link

**Comment by gricey432** [comment]
Also, you've already posted that on #27 where @entomb offered to help and you never replied
